/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/*
 * Copyright (c) 2025 MediaTek Inc.
 *               KY Liu <ky.liu@mediatek.com>
 * Coprright (c) 2026 Jolla Mobile Ltd
 *               Nikolai Burov <nikolai.burov@jolla.com>
 */

#ifndef _DT_BINDINGS_CLK_MT6858_H
#define _DT_BINDINGS_CLK_MT6858_H

/* CKSYS_REG */
#define CLK_TOP_MAINPLL_D3				0
#define CLK_TOP_MAINPLL_D4				1
#define CLK_TOP_MAINPLL_D4_D2				2
#define CLK_TOP_MAINPLL_D4_D4				3
#define CLK_TOP_MAINPLL_D4_D8				4
#define CLK_TOP_MAINPLL_D5				5
#define CLK_TOP_MAINPLL_D5_D2				6
#define CLK_TOP_MAINPLL_D5_D4				7
#define CLK_TOP_MAINPLL_D5_D8				8
#define CLK_TOP_MAINPLL_D6				9
#define CLK_TOP_MAINPLL_D6_D2				10
#define CLK_TOP_MAINPLL_D6_D8				11
#define CLK_TOP_MAINPLL_D7				12
#define CLK_TOP_MAINPLL_D7_D2				13
#define CLK_TOP_MAINPLL_D7_D4				14
#define CLK_TOP_MAINPLL_D7_D8				15
#define CLK_TOP_UNIVPLL_D2				16
#define CLK_TOP_UNIVPLL_D3				17
#define CLK_TOP_UNIVPLL_D4				18
#define CLK_TOP_UNIVPLL_D4_D2				19
#define CLK_TOP_UNIVPLL_D4_D4				20
#define CLK_TOP_UNIVPLL_D4_D8				21
#define CLK_TOP_UNIVPLL_D5				22
#define CLK_TOP_UNIVPLL_D5_D2				23
#define CLK_TOP_UNIVPLL_D5_D4				24
#define CLK_TOP_UNIVPLL_D6				25
#define CLK_TOP_UNIVPLL_D6_D2				26
#define CLK_TOP_UNIVPLL_D6_D4				27
#define CLK_TOP_UNIVPLL_D6_D8				28
#define CLK_TOP_UNIVPLL_D6_D16				29
#define CLK_TOP_UNIVPLL_D7				30
#define CLK_TOP_UNIVPLL_D7_D2				31
#define CLK_TOP_UNIVPLL_192M				32
#define CLK_TOP_UNIVPLL_192M_D2				33
#define CLK_TOP_UNIVPLL_192M_D4				34
#define CLK_TOP_UNIVPLL_192M_D8				35
#define CLK_TOP_UNIVPLL_192M_D16			36
#define CLK_TOP_UNIVPLL_192M_D32			37
#define CLK_TOP_UNIVPLL_192M_D10			38
#define CLK_TOP_APLL1_D2				39
#define CLK_TOP_APLL1_D4				40
#define CLK_TOP_APLL1_D8				41
#define CLK_TOP_APLL2_D2				42
#define CLK_TOP_APLL2_D4				43
#define CLK_TOP_APLL2_D8				44
#define CLK_TOP_MSDCPLL_D2				45
#define CLK_TOP_OSC					46
#define CLK_TOP_OSC_D2					47
#define CLK_TOP_OSC_D4					48
#define CLK_TOP_OSC_D7					49
#define CLK_TOP_OSC_D8					50
#define CLK_TOP_OSC_D10					51
#define CLK_TOP_OSC_D16					52
#define CLK_TOP_MMPLL_D4				53
#define CLK_TOP_MMPLL_D4_D2				54
#define CLK_TOP_MMPLL_D4_D4				55
#define CLK_TOP_MMPLL_D5				56
#define CLK_TOP_MMPLL_D5_D2				57
#define CLK_TOP_MMPLL_D6				58
#define CLK_TOP_MMPLL_D6_D2				59
#define CLK_TOP_MMPLL_D7				60
#define CLK_TOP_MMPLL_D9				61
#define CLK_TOP_AXI					62
#define CLK_TOP_AXI_P					63
#define CLK_TOP_AXI_UFS					64
#define CLK_TOP_BUS_AXIMEM				65
#define CLK_TOP_DISP0					66
#define CLK_TOP_MMINFRA					67
#define CLK_TOP_MMUP					68
#define CLK_TOP_UART					69
#define CLK_TOP_SPI0					70
#define CLK_TOP_SPI1					71
#define CLK_TOP_SPI2					72
#define CLK_TOP_SPI3					73
#define CLK_TOP_SPI4					74
#define CLK_TOP_SPI5					75
#define CLK_TOP_SPI6					76
#define CLK_TOP_SPI7					77
#define CLK_TOP_MSDC_MACRO_1P				78
#define CLK_TOP_MSDC30_1				79
#define CLK_TOP_MSDC30_1_HCLK				80
#define CLK_TOP_AUD_INTBUS				81
#define CLK_TOP_ATB					82
#define CLK_TOP_DISP_PWM				83
#define CLK_TOP_USB_TOP					84
#define CLK_TOP_USB_XHCI				85
#define CLK_TOP_I2C					86
#define CLK_TOP_SENINF					87
#define CLK_TOP_SENINF1					88
#define CLK_TOP_SENINF2					89
#define CLK_TOP_AUD_ENGEN1				90
#define CLK_TOP_AUD_ENGEN2				91
#define CLK_TOP_AES_UFSFDE				92
#define CLK_TOP_UFS					93
#define CLK_TOP_AUD_1					94
#define CLK_TOP_AUD_2					95
#define CLK_TOP_DPMAIF_MAIN				96
#define CLK_TOP_VENC					97
#define CLK_TOP_VDEC					98
#define CLK_TOP_PWM					99
#define CLK_TOP_AUDIO_H					100
#define CLK_TOP_MCUPM					101
#define CLK_TOP_MEM_SUB					102
#define CLK_TOP_MEM_SUB_P				103
#define CLK_TOP_MEM_SUB_UFS				104
#define CLK_TOP_EMI_N					105
#define CLK_TOP_DSI_OCC					106
#define CLK_TOP_AP2CONN_HOST				107
#define CLK_TOP_IMG1					108
#define CLK_TOP_IPE					109
#define CLK_TOP_CAM					110
#define CLK_TOP_CAMTM					111
#define CLK_TOP_EMI_INTERFACE_546			112
#define CLK_TOP_MFG_REF					113
#define CLK_TOP_MFGSC_REF				114
#define CLK_TOP_EFUSE					115
#define CLK_TOP_UNIPLL_SES				116
#define CLK_TOP_DRAMULP					117
#define CLK_TOP_USB_FRMCNT				118
#define CLK_TOP_APLL_I2SIN1_MCK				119
#define CLK_TOP_APLL_I2SIN2_MCK				120

/* INFRA_INFRACFG_AO_REG */
#define CLK_IFRAO_CCIF1_AP				0
#define CLK_IFRAO_CCIF1_MD				1
#define CLK_IFRAO_CCIF_AP				2
#define CLK_IFRAO_CCIF_MD				3
#define CLK_IFRAO_CLDMA_BCLK				4
#define CLK_IFRAO_CCIF5_MD				5
#define CLK_IFRAO_CCIF2_AP				6
#define CLK_IFRAO_CCIF2_MD				7
#define CLK_IFRAO_DPMAIF_MAIN				8
#define CLK_IFRAO_CCIF4_MD				9
#define CLK_IFRAO_RG_MMW_DPMAIF26M			10

/* APMIXEDSYS */
#define CLK_APMIXED_ARMPLL_LL				0
#define CLK_APMIXED_ARMPLL_BL				1
#define CLK_APMIXED_CCIPLL				2
#define CLK_APMIXED_MAINPLL				3
#define CLK_APMIXED_UNIVPLL				4
#define CLK_APMIXED_MSDCPLL				5
#define CLK_APMIXED_MMPLL				6
#define CLK_APMIXED_TVDPLL				7
#define CLK_APMIXED_EMIPLL				8
#define CLK_APMIXED_ADSPPLL				9
#define CLK_APMIXED_APLL1				10
#define CLK_APMIXED_APLL2				11

/* PERICFG_AO */
#define CLK_PERAO_UART0					0
#define CLK_PERAO_UART1					1
#define CLK_PERAO_UART2					2
#define CLK_PERAO_UART3					3
#define CLK_PERAO_PWM_H					4
#define CLK_PERAO_PWM_B					5
#define CLK_PERAO_PWM_FB1				6
#define CLK_PERAO_PWM_FB2				7
#define CLK_PERAO_PWM_FB3				8
#define CLK_PERAO_PWM_FB4				9
#define CLK_PERAO_DISP_PWM0				10
#define CLK_PERAO_DISP_PWM1				11
#define CLK_PERAO_SPI0_B				12
#define CLK_PERAO_SPI1_B				13
#define CLK_PERAO_SPI2_B				14
#define CLK_PERAO_SPI3_B				15
#define CLK_PERAO_SPI4_B				16
#define CLK_PERAO_SPI5_B				17
#define CLK_PERAO_SPI6_B				18
#define CLK_PERAO_SPI7_B				19
#define CLK_PERAO_I2C					20
#define CLK_PERAO_DMA_B					21
#define CLK_PERAO_MSDC1					22
#define CLK_PERAO_MSDC1_H				23
#define CLK_PERAO_MSDC1_MST_F				24
#define CLK_PERAO_MSDC1_SLV_H				25
#define CLK_PERAO_AUDIO0				26
#define CLK_PERAO_AUDIO1				27
#define CLK_PERAO_AUDIO2				28

/* AFE */
#define CLK_AFE_AUD_PAD_TOP_MOSI_EN			0
#define CLK_AFE_DL0_DAC_TML				1
#define CLK_AFE_DL0_DAC_HIRES				2
#define CLK_AFE_DL0_DAC					3
#define CLK_AFE_DL0_PREDIS				4
#define CLK_AFE_DL0_NLE					5
#define CLK_AFE_PCM1					6
#define CLK_AFE_PCM0					7
#define CLK_AFE_CM1					8
#define CLK_AFE_CM0					9
#define CLK_AFE_STF					10
#define CLK_AFE_HW_GAIN23				11
#define CLK_AFE_HW_GAIN01				12
#define CLK_AFE_UL1_ADC_HIRES_TML			13
#define CLK_AFE_UL1_ADC_HIRES				14
#define CLK_AFE_UL1_TML					15
#define CLK_AFE_UL1_ADC					16
#define CLK_AFE_UL0_ADC_HIRES_TML			17
#define CLK_AFE_UL0_ADC_HIRES				18
#define CLK_AFE_UL0_TML					19
#define CLK_AFE_UL0_ADC					20
#define CLK_AFE_ETDM_IN4				21
#define CLK_AFE_ETDM_IN2				22
#define CLK_AFE_ETDM_IN1				23
#define CLK_AFE_ETDM_OUT4				24
#define CLK_AFE_ETDM_OUT2				25
#define CLK_AFE_ETDM_OUT1				26
#define CLK_AFE_GENERAL3_ASRC				27
#define CLK_AFE_GENERAL2_ASRC				28
#define CLK_AFE_GENERAL1_ASRC				29
#define CLK_AFE_GENERAL0_ASRC				30
#define CLK_AFE_CONNSYS_I2S_ASRC			31
#define CLK_AFE_AUDIO_HOPPING				32
#define CLK_AFE_AUDIO_F26M				33
#define CLK_AFE_APLL1					34
#define CLK_AFE_APLL2					35
#define CLK_AFE_H208M					36
#define CLK_AFE_APLL_TUNER2				37
#define CLK_AFE_APLL_TUNER1				38

/* IMP_IIC_WRAP_C */
#define CLK_IMPC_I2C1					0
#define CLK_IMPC_I2C3					1
#define CLK_IMPC_I2C5					2
#define CLK_IMPC_I2C6					3
#define CLK_IMPC_I2C10					4
#define CLK_IMPC_I2C12					5

/* UFSCFG_AO */
#define CLK_UFSAO_UNIPRO_TX_SYM				0
#define CLK_UFSAO_UNIPRO_SYS				1
#define CLK_UFSAO_UNIPRO_SAP_CFG			2

/* UFSCFG_PDN */
#define CLK_UFSPDN_UFSHCI_UFS				0
#define CLK_UFSPDN_UFSHCI_AES				1
#define CLK_UFSPDN_UFSHCI_UFS_AHB			2
#define CLK_UFSPDN_UFS_26M				3

/* IMP_IIC_WRAP_ES */
#define CLK_IMPES_I2C4					0
#define CLK_IMPES_I2C7					1
#define CLK_IMPES_I2C8					2

/* IMP_IIC_WRAP_S */
#define CLK_IMPS_I2C0					0
#define CLK_IMPS_I2C2					1
#define CLK_IMPS_I2C9					2
#define CLK_IMPS_I2C11					3

/* DISPSYS_CONFIG */
#define CLK_MM_DISP_OVL0_2L				0
#define CLK_MM_DISP_OVL1_2L				1
#define CLK_MM_DISP_OVL2_2L				2
#define CLK_MM_DISP_RSZ1				3
#define CLK_MM_DISP_RSZ0				4
#define CLK_MM_DISP_TDSHP0				5
#define CLK_MM_DISP_C3D0				6
#define CLK_MM_DISP_COLOR0				7
#define CLK_MM_DISP_CCORR0				8
#define CLK_MM_DISP_CCORR1				9
#define CLK_MM_DISP_AAL0				10
#define CLK_MM_DISP_GAMMA0				11
#define CLK_MM_DISP_POSTMASK0				12
#define CLK_MM_DISP_DITHER0				13
#define CLK_MM_DISP_TDSHP1				14
#define CLK_MM_DISP_C3D1				15
#define CLK_MM_DISP_CCORR2				16
#define CLK_MM_DISP_CCORR3				17
#define CLK_MM_DISP_GAMMA1				18
#define CLK_MM_DISP_DITHER1				19
#define CLK_MM_DISP_DSC_WRAP0				20
#define CLK_MM_DISP_DSI0				21
#define CLK_MM_DISP_WDMA1				22
#define CLK_MM_DISP_APB_BUS				23
#define CLK_MM_DISP_FAKE_ENG0				24
#define CLK_MM_DISP_FAKE_ENG1				25
#define CLK_MM_DISP_MUTEX0				26
#define CLK_MM_SMI_COMMON				27
#define CLK_MM_DSI0					28
#define CLK_MM_26M					29

/* IMGSYS1 */
#define CLK_IMGSYS1_LARB9				0
#define CLK_IMGSYS1_LARB10				1
#define CLK_IMGSYS1_DIP					2

/* IMGSYS2 */
#define CLK_IMGSYS2_LARB9				0
#define CLK_IMGSYS2_MFB					1
#define CLK_IMGSYS2_WPE					2
#define CLK_IMGSYS2_MSS					3

/* VDEC_GCON_BASE */
#define CLK_VDE2_LAT_CKEN				0
#define CLK_VDE2_LAT_ACTIVE				1
#define CLK_VDE2_LAT_CKEN_ENG				2
#define CLK_VDE2_VDEC_CKEN				3
#define CLK_VDE2_VDEC_ACTIVE				4
#define CLK_VDE2_VDEC_CKEN_ENG				5

/* VENC_GCON */
#define CLK_VEN1_CKE0_LARB				0
#define CLK_VEN1_CKE1_VENC				1
#define CLK_VEN1_CKE2_JPGENC				2
#define CLK_VEN1_CKE5_GALS				3

/* VLP_CKSYS_TOP */
#define CLK_VLP_TOP_SCP					0
#define CLK_VLP_TOP_PWRAP_ULPOSC			1
#define CLK_VLP_TOP_SPMI_P_MST				2
#define CLK_VLP_TOP_SPMI_M_MST				3
#define CLK_VLP_TOP_DVFSRC				4
#define CLK_VLP_TOP_PWM_VLP				5
#define CLK_VLP_TOP_AXI_VLP				6
#define CLK_VLP_TOP_SYSTIMER_26M			7
#define CLK_VLP_TOP_SSPM				8
#define CLK_VLP_TOP_SSPM_F26M				9
#define CLK_VLP_TOP_SRCK				10
#define CLK_VLP_TOP_SCP_SPI				11
#define CLK_VLP_TOP_SCP_IIC				12
#define CLK_VLP_TOP_SCP_IIC_HIGH_SPD			13
#define CLK_VLP_TOP_SSPM_ULPOSC				14
#define CLK_VLP_TOP_TIA_ULPOSC				15
#define CLK_VLP_TOP_APXGPT_26M				16
#define CLK_VLP_TOP_CAMTG0				17
#define CLK_VLP_TOP_CAMTG1				18
#define CLK_VLP_TOP_CAMTG2				19
#define CLK_VLP_TOP_CAMTG3				20
#define CLK_VLP_TOP_KP_IRQ_GEN				21
#define CLK_VLP_TOP_SSR_PKA				22
#define CLK_VLP_TOP_SSR_DMA				23
#define CLK_VLP_TOP_SSR_KDF				24
#define CLK_VLP_TOP_SSR_RNG				25

/* CAMSYS_MAIN */
#define CLK_CAM_M_LARB13				0
#define CLK_CAM_M_LARB14				1
#define CLK_CAM_M_CAM					2
#define CLK_CAM_M_CAMTG					3
#define CLK_CAM_M_SENINF				4
#define CLK_CAM_M_CAMSV1				5
#define CLK_CAM_M_CAMSV2				6
#define CLK_CAM_M_CAMSV3				7
#define CLK_CAM_M_CAM2MM_GALS				8
#define CLK_CAM_M_PDA					9

/* CAMSYS_RAWA */
#define CLK_CAM_RA_LARBX				0
#define CLK_CAM_RA_CAM					1
#define CLK_CAM_RA_CAMTG				2

/* CAMSYS_RAWB */
#define CLK_CAM_RB_LARBX				0
#define CLK_CAM_RB_CAM					1
#define CLK_CAM_RB_CAMTG				2

/* IPESYS */
#define CLK_IPE_LARB20					0
#define CLK_IPE_SMI_SUBCOM				1
#define CLK_IPE_FD					2
#define CLK_IPE_RSC					3

/* MMINFRA_CONFIG */
#define CLK_MMINFRA_GCE_D				0
#define CLK_MMINFRA_GCE_M				1
#define CLK_MMINFRA_GCE_26M				2

/* MDPSYS_CONFIG */
#define CLK_MDP_MUTEX0					0
#define CLK_MDP_APB_BUS					1
#define CLK_MDP_SMI0					2
#define CLK_MDP_RDMA0					3
#define CLK_MDP_FG0					4
#define CLK_MDP_HDR0					5
#define CLK_MDP_AAL0					6
#define CLK_MDP_RSZ0					7
#define CLK_MDP_TDSHP0					8
#define CLK_MDP_COLOR0					9
#define CLK_MDP_WROT0					10
#define CLK_MDP_FAKE_ENG0				11
#define CLK_MDP_DLI_ASYNC0				12
#define CLK_MDP_RSZ2					13
#define CLK_MDP_WROT2					14
#define CLK_MDP_DLO_ASYNC0				15
#define CLK_MDP_FMM_IMG_DL_ASYNC0			16
#define CLK_MDP_FMM_IMG_DL_ASYNC1			17
#define CLK_MDP_FIMG_IMG_DL_ASYNC0			18
#define CLK_MDP_FIMG_IMG_DL_ASYNC1			19

#endif /* _DT_BINDINGS_CLK_MT6858_H */
